version: '3.9'

volumes:
  db-data:

services:
  db:
    image: postgres:15.4
    healthcheck:
      test: pg_isready --dbname=app --username=postgres 
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  sqlx_migrate:
    build: 
      dockerfile: sqlx_migrate.Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
    depends_on:
      db:
        condition: service_healthy
  
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app
    ports:
      - 8000:8000
    depends_on:
      sqlx_migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2.1
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    ports:
      - 24224:24224
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config/fluent-bit-parsers.conf:/fluent-bit/etc/parsers.conf
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
